[theme]
name = "Black Iris"

[theme.base]
white = "#fcfcfa"
black = "#141414"
grey = "#939293"
blue = "#1371be"
red = "#ff6188"
yellow = "#ffd866"
orange = "#D19A66"
green = "#a9dc76"
purple = "#C678DD"
cyan = "#32929f"
magenta = "#ab9df2"

[theme.syntax]
attribute = "$orange"
builtinType = "$cyan"
comment = "#5C6370"
constant = "#D62C2C"
constructor = "$yellow"
embedded = "$cyan"
enum = "#9263D3"
enum-member = "$red"
enumMember = "#AA63D3"
escape = "$cyan"
field = "$red"
function = "$blue"
"function.method" = "$blue"
interface = "#DD46C2"
keyword = "#14E5D4"
macro = "#28A9FF"
method = "#28A9FF"
number = "$yellow"
operator = "#EEEEEE60"
property = "#FF7135"
selfKeyword = "#14E5D4"
string = "#a9dc76"
struct = "#A95EFF"
structure = "#A95EFF"
symbol = "$yellow"
type = "#A95EFF"
"type.builtin" = "$cyan"
typeAlias = "#b079ee"
variable = "#FF478D"
"variable.other.member" = "$red"
"variable.parameter" = "#FF478D"

[theme.ui]
"activity.background" = "$black"
"activity.current" = "#353535"
"completion.background" = "$black"
"completion.current" = "#353535"
"editor.background" = "$black"
"editor.caret" = "#ffb3d6"
"editor.current_line" = "#aaaaaa0c"
"editor.dim" = "#bfabfa"
"editor.focus" = "$black"
"editor.foreground" = "#dedede"
"editor.link" = "$cyan"
"editor.selection" = "#222222"
"error_lens.error.background" = "#141414"
"error_lens.error.foreground" = "#FA3232"
"error_lens.other.background" = "#141414"
"error_lens.other.foreground" = "#b0b0b0"
"error_lens.warning.background" = "#141414"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#595959"
"inlay_hint.background" = "#221f22"
"inlay_hint.foreground" = "#969694"
"lapce.active_tab" = "#161616"
"lapce.border" = "#1E1E1E"
"lapce.dropdown_shadow" = "#020202"
"lapce.error" = "#ff6188"
"lapce.inactive_tab" = "#101014"
"lapce.scroll_bar" = "$magenta"
"lapce.warn" = "$red"
"markdown.blockquote" = "#a9dc76"
"palette.background" = "$black"
"palette.current" = "#262626"
"panel.background" = "$black"
"panel.current" = "#262626"
"panel.hovered" = "#595959"
"source_control.added" = "#a9dc76"
"source_control.modified" = "#78dce8"
"source_control.removed" = "#727072"
"status.background" = "$black"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"
"terminal.background" = "#121212"
"terminal.black" = "#141414"
"terminal.blue" = "#fc9867"
"terminal.bright_black" = "#161616"
"terminal.bright_blue" = "#fc9867"
"terminal.bright_cyan" = "#78dce8"
"terminal.bright_green" = "#a9dc76"
"terminal.bright_magenta" = "#ab9df2"
"terminal.bright_red" = "#ff6188"
"terminal.bright_white" = "#fcfcfa"
"terminal.bright_yellow" = "#ffd866"
"terminal.cursor" = "#ffb638"
"terminal.cyan" = "#78dce8"
"terminal.foreground" = "#fcfcfa"
"terminal.green" = "#a9dc76"
"terminal.magenta" = "#ab9df2"
"terminal.red" = "#ff6188"  
"terminal.white" = "#fcfcfa"  
"terminal.yellow" = "#ffd866"  

[ui]
font-family = "SauceCodePro NF"
font-size = 13
header-height = 35
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 4
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
