name = "black-iris"
display-name = "Black Iris"
description = "A dark theme with pastel colors"
version = "0.2.0"
author = "Yukusai"
icon = "black-iris.png"
repository = "p-yukusai/black-iris"
themes = ["black-iris.toml"]
