name = "black-iris"
display-name = "Black Iris"
description = "A dark theme with pastel colors"
version = "1.0.0"
author = "Yukusai"
icon = "black-iris.png"
repository = "https://github.com/p-yukusai/black-iris"
themes = ["black-iris.toml"]
