name = "black-iris"
version = "0.1.11"
display-name = "Black Iris"
description = "A dark theme with pastel colors"
author = "p-yukusai"
icon = "logo.png"
repository = "https://github.com/p-yukusai/black-iris"
color-themes = ["black-iris.toml"]

